const canvas=document.getElementById('game'); const ctx2=canvas.getContext('2d');
const hud={score:document.getElementById('score'),combo:document.getElementById('combo'),acc:document.getElementById('acc')};
let W,H; const lanes=['kick','snare','hihat','crash']; const colors={kick:'#4cb2ff',snare:'#63e663',hihat:'#ffd54d',crash:'#ff5f52'};
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;ctx2.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)} addEventListener('resize',resize);resize();
const state={running:false,start:0,score:0,combo:0,hits:0,accurate:0,notes:[]};
const bpm=92, spb=60/bpm; const pattern=[['hihat','kick'],['hihat'],['hihat','snare'],['hihat'],['hihat','kick'],['hihat'],['hihat','snare'],['hihat']];
function buildNotes(){state.notes=[];let t=2; for(let bar=0;bar<8;bar++){ for(let i=0;i<pattern.length;i++){ for(const type of pattern[i]) state.notes.push({id:crypto.randomUUID(),type,time:t+i*spb/2,judged:false,hit:false}); } t+=4*spb; }}
class AudioEngine{constructor(){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.8;this.comp=this.ctx.createDynamicsCompressor();this.master.connect(this.comp);this.comp.connect(this.ctx.destination)}async unlock(){if(this.ctx.state!=='running')await this.ctx.resume()}play(type,v=1){const t=this.ctx.currentTime;const o=this.ctx.createOscillator();const g=this.ctx.createGain();o.connect(g);g.connect(this.master);if(type==='kick'){o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(45,t+.14);g.gain.setValueAtTime(.9*v,t);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.type='sine';o.start(t);o.stop(t+.17);}else if(type==='snare'){const b=this.ctx.createBuffer(1,22050,this.ctx.sampleRate);const d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const n=this.ctx.createBufferSource();n.buffer=b;const hp=this.ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=1400;n.connect(hp);hp.connect(g);g.gain.setValueAtTime(.55*v,t);g.gain.exponentialRampToValueAtTime(.001,t+.09);n.start(t);n.stop(t+.1);}else if(type==='hihat'){const b=this.ctx.createBuffer(1,11025,this.ctx.sampleRate);const d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const n=this.ctx.createBufferSource();n.buffer=b;const hp=this.ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=7000;n.connect(hp);hp.connect(g);g.gain.setValueAtTime(.3*v,t);g.gain.exponentialRampToValueAtTime(.001,t+.04);n.start(t);n.stop(t+.05);} else {o.frequency.value=560;o.type='triangle';g.gain.setValueAtTime(.5*v,t);g.gain.exponentialRampToValueAtTime(.001,t+.5);o.start(t);o.stop(t+.5);} }
}
const audio=new AudioEngine();
function hit(type,vel=1){audio.play(type,vel); if(!state.running)return; const now=performance.now()/1000-state.start; const c=state.notes.filter(n=>!n.judged&&n.type===type).map(n=>({n,d:(now-n.time)*1000})).filter(x=>Math.abs(x.d)<180).sort((a,b)=>Math.abs(a.d)-Math.abs(b.d))[0]; if(!c){state.combo=0;update();return;} c.n.judged=true;c.n.hit=true;const a=Math.abs(c.d);let pts=0;if(a<=35){pts=1000;state.accurate++;}else if(a<=70){pts=750;state.accurate++;}else if(a<=110){pts=500}else pts=150;state.score+=pts;state.combo++;state.hits++;update();}
function update(){hud.score.textContent='Score '+Math.round(state.score);hud.combo.textContent='Combo '+state.combo;hud.acc.textContent='Acc '+(state.hits?Math.round(state.accurate/state.hits*100):100)+'%'}
addEventListener('keydown',e=>{const m={d:'kick',f:'snare',j:'hihat',k:'crash'};const t=m[e.key.toLowerCase()]; if(t)hit(t,1)});
document.querySelectorAll('#touch button').forEach(b=>b.addEventListener('pointerdown',()=>hit(b.dataset.hit,1)));
document.getElementById('play').onclick=async()=>{await audio.unlock();state.running=true;state.start=performance.now()/1000;state.score=0;state.combo=0;state.hits=0;state.accurate=0;buildNotes();update();};
function draw(t){ctx2.clearRect(0,0,innerWidth,innerHeight);const top=innerHeight*.14,bottom=innerHeight*.67,left=innerWidth*.28,right=innerWidth*.72;ctx2.fillStyle='rgba(5,8,16,.55)';ctx2.beginPath();ctx2.moveTo(left,top);ctx2.lineTo(right,top);ctx2.lineTo(innerWidth*.83,bottom);ctx2.lineTo(innerWidth*.17,bottom);ctx2.closePath();ctx2.fill();ctx2.strokeStyle='rgba(255,255,255,.25)'; for(let i=0;i<=4;i++){const x1=left+(right-left)/4*i,x2=innerWidth*.17+(innerWidth*.66)/4*i;ctx2.beginPath();ctx2.moveTo(x1,top);ctx2.lineTo(x2,bottom);ctx2.stroke();}
ctx2.strokeStyle='rgba(255,190,110,.9)';ctx2.lineWidth=3;ctx2.beginPath();ctx2.moveTo(innerWidth*.17,bottom);ctx2.lineTo(innerWidth*.83,bottom);ctx2.stroke();
// drums simple
ctx2.fillStyle='#2a1a12';ctx2.fillRect(0,innerHeight*.68,innerWidth,innerHeight*.32);const drums=[['snare',innerWidth*.36,innerHeight*.8,75],['kick',innerWidth*.5,innerHeight*.82,95],['tom',innerWidth*.62,innerHeight*.8,75]];for(const d of drums){ctx2.beginPath();ctx2.fillStyle='#ddd';ctx2.arc(d[1],d[2],d[3],0,Math.PI*2);ctx2.fill();ctx2.strokeStyle='#111';ctx2.stroke();}
// feet/pedals
ctx2.fillStyle='#777';ctx2.fillRect(innerWidth*.36,innerHeight*.93,60,12);ctx2.fillRect(innerWidth*.53,innerHeight*.92,60,12);ctx2.fillStyle='#111';ctx2.fillRect(innerWidth*.36,innerHeight*.9,58,26);ctx2.fillRect(innerWidth*.53,innerHeight*.89,58,26);
if(state.running){const now=performance.now()/1000-state.start; for(const n of state.notes){if(n.judged)continue; const dt=n.time-now; const p=1-dt/2; if(p<0||p>1.05)continue; const y=top+(bottom-top)*p; const li=lanes.indexOf(n.type); const x=innerWidth*.22+li*(innerWidth*.56/3); ctx2.fillStyle=colors[n.type];ctx2.beginPath();ctx2.arc(x,y,14,0,Math.PI*2);ctx2.fill(); if(now-n.time>.18){n.judged=true;state.combo=0;state.hits++;update();}}}
requestAnimationFrame(draw)} requestAnimationFrame(draw);
